/**
 * TraceFlow RMG — Centralized Design Tokens
 * Strictly follows Microsoft Power Automate & Fluent 2 Design System Standards.
 * 
 * Signature Palette:
 * - Brand Primary: #0066FF (Power Automate Electric Cobalt Blue)
 * - Accent Hover: #0052CC / Active: #003D99
 * - Canvas Background: #F0F4F8 (Fluent 2 Light Neutral Soft Canvas)
 * - Navigation Rail: #FFFFFF with subtle #E2E8F0 border
 * - Active Selection: #EFF6FC with #0066FF solid left bar indicator
 * - Cards & Surfaces: #FFFFFF with soft elevation (shadow-sm)
 * - Corner Radii: rounded-lg (8px) for modern cloud look
 */

export const UI_TOKENS = {
  typography: {
    fontFamily: "'Segoe UI', -apple-system, BlinkMacSystemFont, Roboto, sans-serif",
    sizes: {
      xs: "text-xs", // 12px
      sm: "text-xs font-normal", // 13px base
      base: "text-sm",
      lg: "text-base font-semibold", // 16px (Card Title)
      xl: "text-lg font-semibold",
      "2xl": "text-xl font-bold text-slate-900 tracking-tight", // 20px
    },
  },
  colors: {
    bg: {
      app: "bg-[#F0F4F8]", // Power Automate signature soft cold canvas
      card: "bg-white",
      tableHeader: "bg-[#F8FAFC]",
      subtle: "bg-slate-50",
    },
    text: {
      primary: "text-slate-900",
      secondary: "text-slate-600",
      muted: "text-slate-400",
      disabled: "text-slate-300",
    },
    border: "border-slate-200/90",
  },
  powerShell: {
    header: "sticky top-0 z-50 h-12 bg-[#0066FF] text-white px-3.5 flex items-center justify-between select-none shadow-xs font-sans",
    waffleButton: "p-1.5 rounded-sm hover:bg-white/15 text-white transition-colors cursor-pointer",
    brandLogo: "w-5.5 h-5.5 shrink-0 flex items-center justify-center text-white",
    brandText: "font-semibold text-white tracking-tight text-sm",
    brandAccent: "text-blue-100 font-bold",
    brandWrapper: "flex items-center gap-3",
    brandTitleClickable: "flex items-center gap-2 cursor-pointer",
    versionBadge: "text-[10px] font-mono font-medium text-blue-100 bg-white/15 px-1.5 py-0.5 rounded border border-white/20 select-none",
    companyBadge: "flex flex-col items-start px-2 py-0.5 rounded-sm hover:bg-white/15 text-white transition-colors cursor-pointer text-left leading-none",
    searchContainer: "flex-1 max-w-xl mx-auto px-4 hidden md:block",
    searchButton: "w-full flex items-center justify-between px-3.5 py-1.5 rounded-md bg-white hover:bg-slate-50 text-xs text-slate-600 transition-all cursor-pointer shadow-xs border border-transparent",
    searchForm: "w-full relative flex items-center",
    searchInput: "w-full pl-8 pr-12 py-1.5 rounded-md bg-white text-xs text-slate-800 placeholder:text-slate-500 shadow-xs border border-transparent focus:border-white focus:outline-none focus:ring-2 focus:ring-white/40 transition-all",
    searchInner: "flex items-center gap-2",
    searchIcon: "w-3.5 h-3.5 text-slate-500",
    searchIconAbsolute: "absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-slate-400 pointer-events-none",
    searchClearButton: "absolute right-7 top-1/2 -translate-y-1/2 p-0.5 rounded hover:bg-slate-100 text-slate-400 hover:text-slate-600 transition-colors cursor-pointer",
    searchPlaceholder: "truncate text-slate-600 font-normal text-xs",
    searchKbd: "hidden lg:inline-block px-1.5 py-0.2 text-[10px] font-mono bg-slate-100 border border-slate-200 text-slate-500 rounded shadow-2xs",
    searchKbdAbsolute: "absolute right-2 top-1/2 -translate-y-1/2 hidden lg:inline-block px-1.5 py-0.2 text-[10px] font-mono bg-slate-100 border border-slate-200 text-slate-500 rounded shadow-2xs pointer-events-none",
    rightContainer: "flex items-center gap-3 relative",
    actionIconsGroup: "flex items-center gap-1",
    actionButton: "p-1.5 rounded-sm hover:bg-white/15 text-white transition-colors cursor-pointer relative",
    notificationDot: "absolute top-1.5 right-1.5 w-1.5 h-1.5 bg-amber-400 rounded-full",
    avatarMenuContainer: "relative",
    avatarButton: "w-8 h-8 rounded-full bg-white text-[#0066FF] flex items-center justify-center font-bold text-xs shadow-xs border-2 border-white/40 hover:border-white cursor-pointer transition-all focus:outline-none",
    flyoutBackdrop: "fixed inset-0 z-40",
    flyoutCard: "absolute right-0 top-11 z-50 w-72 bg-white text-slate-800 rounded-sm shadow-xl border border-slate-200 py-3 px-4 font-sans animate-in fade-in duration-100",
    flyoutHeader: "flex items-center justify-between pb-3 border-b border-slate-100 text-xs",
    flyoutCompany: "font-semibold text-slate-700 truncate max-w-[160px]",
    flyoutSignOut: "text-[#0066FF] hover:underline font-medium cursor-pointer",
    flyoutBody: "flex items-start gap-3 pt-3",
    flyoutAvatar: "w-12 h-12 rounded-full bg-[#0066FF] text-white flex items-center justify-center font-bold text-base shadow-sm shrink-0",
    flyoutDetails: "space-y-0.5 min-w-0",
    flyoutName: "text-sm font-bold text-slate-900 leading-tight truncate",
    flyoutEmail: "text-[11px] text-slate-500 truncate",
    flyoutLinks: "pt-1.5 space-y-0.5 text-xs",
    flyoutLink: "text-[#0066FF] hover:underline block text-[11px]",
    empIdBadge: "font-mono text-[10px] bg-white/20 px-1 py-0.2 rounded text-white font-medium",
  },
  appLayout: {
    wrapper: "min-h-screen bg-[#F0F4F8] text-slate-900 flex flex-col font-sans",
    body: "flex flex-1",
    workspaceOpen: "flex-1 ml-60 transition-all duration-200 flex flex-col min-w-0",
    workspaceCollapsed: "flex-1 ml-14 transition-all duration-200 flex flex-col min-w-0",
    workspaceFull: "flex-1 ml-0 transition-all duration-200 flex flex-col min-w-0",
    subHeader: "sticky top-12 z-30 h-8 bg-white border-b border-slate-200/80 px-6 flex items-center justify-between shadow-2xs",
    breadcrumbNav: "flex items-center gap-1.5 text-xs text-slate-400 font-medium",
    breadcrumbActive: "text-slate-900 font-semibold",
    breadcrumbLink: "hover:text-[#0066FF] transition-colors",
    breadcrumbSeparator: "w-3.5 h-3.5 text-slate-400 shrink-0",
    main: "flex-1 pt-2 px-6 pb-6 overflow-x-hidden",
    mainContent: "w-full space-y-3",
  },
  launcherModal: {
    backdrop: "fixed inset-0 z-50 flex items-start justify-center pt-12 sm:pt-16 bg-slate-900/50 backdrop-blur-xs transition-opacity animate-in fade-in duration-150 p-4",
    container: "w-full max-w-4xl bg-white rounded-xl shadow-2xl ring-1 ring-slate-900/10 border border-slate-200/80 overflow-hidden flex flex-col max-h-[85vh]",
    header: "px-6 py-3.5 border-b border-slate-100 flex items-center justify-between bg-white",
    headerLeft: "flex items-center gap-3",
    headerIconBox: "w-9 h-9 rounded-lg bg-gradient-to-b from-[#0066FF] to-[#0052CC] text-white flex items-center justify-center font-bold shadow-xs shadow-blue-500/20",
    headerIcon: "w-4.5 h-4.5 fill-current",
    headerTitle: "text-sm font-bold text-slate-900 tracking-tight flex items-center gap-2",
    headerCountBadge: "text-[11px] font-semibold text-slate-500 bg-slate-100 px-2 py-0.5 rounded-full",
    headerSubtitle: "text-[11px] text-slate-500 mt-0.5",
    closeButton: "p-1.5 rounded-lg hover:bg-slate-100 text-slate-400 hover:text-slate-700 transition-colors cursor-pointer flex items-center gap-1.5",
    closeIcon: "w-4 h-4",
    escBadge: "text-[10px] font-mono font-medium text-slate-400 bg-slate-100 px-1.5 py-0.5 rounded border border-slate-200",
    searchBar: "px-6 py-3 border-b border-slate-100 bg-slate-50/70 flex items-center justify-between gap-3",
    searchWrapper: "relative flex-1 flex items-center",
    searchIcon: "absolute left-3.5 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400 pointer-events-none",
    searchInput: "w-full pl-10 pr-4 py-2 bg-white border border-slate-200 rounded-lg text-xs text-slate-800 placeholder:text-slate-400 focus:outline-none focus:border-[#0066FF] focus:ring-2 focus:ring-[#0066FF]/15 transition-all shadow-2xs",
    gridContainer: "p-6 overflow-y-auto flex-1 custom-scrollbar bg-[#F8FAFC]",
    grid: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3.5",
    card: "p-4 bg-white border border-slate-200/90 hover:border-[#0066FF] rounded-lg transition-all duration-200 cursor-pointer group shadow-2xs hover:shadow-md hover:shadow-blue-500/5 hover:-translate-y-0.5 flex flex-col justify-between text-left",
    cardTop: "space-y-2",
    cardTopHeader: "flex items-center justify-between",
    cardIconBox: "w-8 h-8 rounded-lg bg-blue-50 text-[#0066FF] group-hover:bg-[#0066FF] group-hover:text-white flex items-center justify-center transition-all duration-200 shadow-2xs group-hover:shadow-xs group-hover:scale-105",
    cardIcon: "w-4 h-4",
    cardBadgeActive: "inline-flex items-center gap-1 text-[10px] font-semibold px-2 py-0.5 rounded-full bg-emerald-50 text-emerald-700 border border-emerald-200/80",
    cardBadgeActiveDot: "w-1.5 h-1.5 rounded-full bg-emerald-500",
    cardBadgeCore: "inline-flex items-center text-[10px] font-semibold px-2 py-0.5 rounded-full bg-blue-50 text-[#0066FF] border border-blue-200/80",
    cardBadge: "text-[10px] font-semibold px-2 py-0.5 rounded-full bg-slate-100 text-slate-600 border border-slate-200",
    cardTitle: "text-xs font-bold text-slate-900 group-hover:text-[#0066FF] transition-colors leading-snug",
    cardDesc: "text-[11px] text-slate-500 leading-relaxed line-clamp-2",
    cardSubList: "mt-2 pt-2 border-t border-slate-100 flex flex-wrap gap-1",
    cardSubPill: "inline-flex items-center text-[10px] px-1.5 py-0.5 rounded bg-slate-50 hover:bg-blue-50 text-slate-600 hover:text-[#0066FF] border border-slate-200/80 transition-colors font-medium",
    cardFooter: "pt-2.5 mt-2.5 border-t border-slate-100 flex items-center justify-between text-[11px] font-medium text-slate-400 group-hover:text-slate-600 transition-colors",
    cardArrow: "w-3.5 h-3.5 text-slate-300 group-hover:text-[#0066FF] transition-all transform group-hover:translate-x-1",
    modalFooter: "px-6 py-2.5 bg-slate-50 border-t border-slate-100 flex items-center justify-between text-[11px] text-slate-500",
    footerHint: "flex items-center gap-1.5",
    footerKbd: "px-1.5 py-0.5 rounded bg-white border border-slate-200 font-mono text-[10px] text-slate-600 shadow-2xs",
    sectionWrapper: "space-y-3",
    sectionHeader: "flex items-center justify-between pb-2 border-b border-slate-200/80",
    sectionHeaderLeft: "flex items-center gap-2",
    sectionStepBadge: "w-5 h-5 rounded-full bg-[#0066FF] text-white flex items-center justify-center text-[10px] font-bold shadow-2xs",
    sectionTitle: "text-xs font-bold text-slate-900 tracking-tight uppercase",
    sectionCountBadge: "text-[10px] font-semibold text-slate-500 bg-slate-100 px-2 py-0.5 rounded-full border border-slate-200/80",
  },
  powerNav: {
    rail: "fixed top-12 bottom-0 left-0 bg-white border-r border-[#EDEBE9] z-40 transition-all duration-200 flex flex-col justify-between select-none shadow-xs font-sans",
    railOpen: "w-60",
    railCollapsed: "w-14",
    createWrapper: "p-3 border-b border-[#EDEBE9]",
    createButton: "w-full flex items-center justify-center gap-2 px-3 py-2 rounded-md bg-[#0066FF] hover:bg-[#0052CC] text-white text-xs font-semibold shadow-xs cursor-pointer transition-colors",
    createButtonCollapsed: "w-full flex items-center justify-center p-2 rounded-md bg-[#0066FF] hover:bg-[#0052CC] text-white shadow-xs cursor-pointer transition-colors",
    quickSection: "space-y-0.5 pb-2 mb-2 border-b border-[#EDEBE9]",
    item: "w-full flex items-center gap-2.5 px-3 py-1.5 rounded-md text-xs font-medium cursor-pointer transition-all text-left relative",
    itemActive: "bg-[#EFF6FC] text-[#0066FF] font-semibold",
    itemInactive: "text-[#201F1E] hover:bg-[#F3F2F1]",
    itemsContainer: "py-2 px-2 overflow-y-auto flex-1 space-y-2 custom-scrollbar",
    collapsedCategoryWrapper: "py-0.5",
    collapsedCategoryButton: "w-full flex items-center justify-center p-2 rounded-md hover:bg-[#EFF6FC] text-[#605E5C] hover:text-[#0066FF] transition-colors cursor-pointer",
    categoryGroup: "space-y-0.5",
    categoryHeader: "px-2.5 pt-2 pb-1 text-[11px] font-bold text-[#605E5C] flex items-center justify-between cursor-pointer hover:text-[#201F1E] transition-colors",
    categoryHeaderLeft: "flex items-center gap-1.5",
    categoryHeaderIcon: "w-3.5 h-3.5 text-[#605E5C] shrink-0",
    categoryHeaderChevron: "w-3 h-3 text-[#A19F9D]",
    categoryItemsList: "space-y-0.5 pt-0.5",
    subItemContainer: "space-y-0.5 py-0.5 pl-3 border-l border-slate-200 ml-4 my-0.5",
    subItem: "w-full flex items-center gap-2 px-2.5 py-1.5 rounded-md text-xs font-normal transition-colors cursor-pointer text-left",
    subItemActive: "text-[#0066FF] font-medium bg-[#EFF6FC] border-l-2 border-[#0066FF] -ml-[1px]",
    subItemInactive: "text-[#605E5C] hover:text-[#201F1E] hover:bg-[#F3F2F1]",
    subItemDotActive: "w-2 h-2 rounded-full bg-[#0066FF] ring-2 ring-blue-100",
    subItemDotInactive: "w-1.5 h-1.5 rounded-full bg-slate-300",
    footer: "p-2 border-t border-[#EDEBE9] bg-white",
    toggleButton: "w-full flex items-center justify-center p-2 rounded-sm hover:bg-[#F3F2F1] text-[#605E5C] hover:text-[#201F1E] text-xs font-medium transition-colors cursor-pointer",
    toggleContent: "flex items-center gap-2",
    toggleText: "text-slate-600 text-xs font-normal",
    itemText: "truncate flex-1",
    subItemText: "truncate",
    chevronWrapperActive: "text-[#0066FF]",
    chevronWrapperInactive: "text-[#A19F9D]",
    iconSm: "w-4 h-4",
    iconSmSlate: "w-4 h-4 text-slate-500",
    iconSmBlue: "w-4 h-4 text-[#0066FF]",
    iconMd: "w-4.5 h-4.5",
    chevronSm: "w-3.5 h-3.5",
    focusBanner: "mx-2 mb-2 p-2 bg-blue-50/70 border border-blue-200/80 rounded-md flex items-center justify-between shadow-2xs",
    focusBannerText: "text-[11px] font-semibold text-blue-900 truncate flex items-center gap-1.5",
    focusBannerClearBtn: "text-[10px] text-blue-600 hover:text-blue-800 hover:bg-blue-100/60 px-1.5 py-0.5 rounded transition-colors font-medium cursor-pointer shrink-0",
  },
  button: {
    base: "inline-flex items-center justify-center font-semibold transition-all focus:outline-none focus:ring-2 focus:ring-offset-1 disabled:opacity-50 disabled:cursor-not-allowed text-xs rounded-lg px-3.5 py-2 cursor-pointer shadow-xs",
    primary: "bg-[#0066FF] hover:bg-[#0052CC] active:bg-[#003D99] text-white focus:ring-[#0066FF] shadow-xs",
    secondary: "bg-white hover:bg-slate-50 active:bg-slate-100 text-slate-700 border border-slate-200 focus:ring-slate-300 shadow-2xs",
    danger: "bg-rose-600 hover:bg-rose-700 text-white focus:ring-rose-500 shadow-xs",
    success: "bg-emerald-600 hover:bg-emerald-700 text-white focus:ring-emerald-500 shadow-xs",
    icon: "p-1.5 rounded-lg hover:bg-slate-100 text-slate-500 hover:text-slate-800 transition-colors cursor-pointer",
    tableAction: "inline-flex items-center gap-1.5 px-2.5 py-1 text-xs font-medium rounded-md border transition-colors cursor-pointer shadow-2xs",
    tableActionPrimary: "border border-blue-200 text-[#0066FF] bg-[#EFF6FC] hover:bg-blue-100/70 transition-all font-semibold shadow-2xs",
    tableActionSecondary: "border border-slate-200 text-slate-700 bg-white hover:bg-slate-50 hover:text-slate-900 transition-all shadow-2xs",
    tableActionDanger: "border border-rose-200 text-rose-600 bg-rose-50/70 hover:bg-rose-100/70 transition-all shadow-2xs",
  },
  badge: {
    base: "inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-medium",
    neutral: "bg-slate-100 text-slate-700 border border-slate-200/80",
    success: "bg-emerald-50 text-emerald-700 border border-emerald-200/80",
    warning: "bg-amber-50 text-amber-800 border border-amber-200/80",
    danger: "bg-rose-50 text-rose-700 border border-rose-200/80",
    info: "bg-[#EFF6FC] text-[#0066FF] border border-[#C7E0F4]",
    code: "font-mono font-semibold bg-[#EFF6FC] text-[#0066FF] border border-[#C7E0F4] rounded-md px-2 py-0.5 text-xs shadow-2xs",
    purple: "bg-purple-50 text-purple-700 border border-purple-200/80",
  },
  form: {
    group: "space-y-1.5",
    label: "block text-xs font-semibold text-slate-700",
    labelDark: "block text-xs font-semibold text-slate-200",
    labelRequired: "text-rose-500 ml-0.5",
    helper: "text-[11px] text-slate-500 mt-1",
    errorMessage: "text-xs font-medium text-rose-600 mt-1.5 flex items-center gap-1",
    errorMessageDark: "text-xs font-medium text-rose-400 mt-1.5 flex items-center gap-1",
    errorIcon: "w-3.5 h-3.5 text-rose-500 shrink-0",
    readonlyBadge: "inline-flex items-center px-1.5 py-0.5 rounded-md text-[10px] font-mono bg-slate-100 text-slate-600 border border-slate-200",
  },
  input: {
    base: "w-full rounded-md border border-slate-300 bg-white px-3 py-1.5 text-xs text-slate-900 placeholder:text-slate-400 focus:border-[#0066FF] focus:outline-none focus:ring-1 focus:ring-[#0066FF] disabled:bg-slate-50 disabled:text-slate-400 disabled:cursor-not-allowed transition-colors shadow-2xs",
    darkBase: "w-full rounded-md border border-slate-700 bg-slate-900 px-3 py-1.5 text-xs text-white placeholder:text-slate-500 focus:border-[#0066FF] focus:outline-none focus:ring-1 focus:ring-[#0066FF] transition-colors",
    select: "rounded-md border border-slate-300 bg-white px-3 py-1.5 text-xs text-slate-800 focus:border-[#0066FF] focus:outline-none focus:ring-1 focus:ring-[#0066FF] shadow-2xs",
    readonly: "bg-slate-50 border-slate-200 text-slate-500 font-mono text-xs cursor-not-allowed",
    error: "border-rose-500 focus:border-rose-500 focus:ring-rose-500",
    errorDark: "border-rose-400 focus:border-rose-400 focus:ring-rose-400",
    iconWrapper: "relative flex items-center",
    iconLeft: "absolute left-2.5 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-slate-400 pointer-events-none",
    iconRight: "absolute right-2.5 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-slate-400 cursor-pointer",
  },
  filter: {
    container: "bg-white border border-slate-200 rounded-md p-3.5 shadow-2xs space-y-3",
    subline: "flex flex-wrap items-center justify-between pt-2.5 border-t border-slate-100 text-xs text-slate-500",
  },
  table: {
    container: "w-full bg-white border border-slate-200 rounded-md shadow-2xs overflow-hidden",
    table: "w-full text-left border-collapse text-xs",
    thead: "bg-[#F8FAFC] border-b border-slate-200 text-[11px] font-semibold text-slate-600 uppercase tracking-wider",
    th: "px-4 py-3",
    tbody: "divide-y divide-slate-100 bg-white",
    tr: "hover:bg-[#F8FAFC] transition-colors",
    trAlt: "even:bg-[#F8FAFC]/50",
    td: "px-4 py-2.5 text-slate-800 align-middle",
    footer: "flex flex-wrap items-center justify-between px-4 py-2.5 border-t border-slate-200 bg-[#F8FAFC] text-xs text-slate-600",
  },
  card: {
    base: "bg-white border border-slate-200 rounded-md p-4 shadow-2xs",
    header: "flex items-center justify-between border-b border-slate-100 pb-2.5 mb-3",
    title: "text-sm font-semibold text-slate-900",
  },
  toggle: {
    base: "relative inline-flex h-6 w-11 shrink-0 rounded-full border-2 border-transparent transition-colors focus:outline-none focus:ring-2 focus:ring-[#0066FF] focus:ring-offset-1 disabled:opacity-60 disabled:cursor-not-allowed cursor-pointer",
    active: "bg-[#0066FF]",
    inactive: "bg-slate-300",
    thumb: "pointer-events-none inline-block h-5 w-5 transform rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out",
    thumbActive: "translate-x-5",
    thumbInactive: "translate-x-0",
  },
  authLayout: {
    wrapper: "min-h-screen bg-[#F0F4F8] flex flex-col justify-center items-center px-4 sm:px-6 lg:px-8 font-sans",
    headerWrapper: "sm:mx-auto sm:w-full sm:max-w-md text-center mb-6",
    logoBox: "inline-flex items-center justify-center h-12 w-12 rounded-xl bg-[#0066FF] text-white font-bold text-xl shadow-md mb-3",
    appTitle: "text-2xl font-bold tracking-tight text-slate-900",
    appSubtitle: "text-xs text-slate-500 mt-1 uppercase tracking-wider font-semibold",
    card: "w-full max-w-md bg-white border border-slate-200 rounded-2xl p-7 shadow-lg",
    cardHeader: "border-b border-slate-100 pb-3.5 mb-5",
    cardTitle: "text-base font-semibold text-slate-900",
    cardSubtitle: "text-xs text-slate-500 mt-0.5",
    generalAlert: "mb-4 p-2.5 rounded-lg bg-rose-50 border border-rose-200 flex items-start gap-2 text-xs text-rose-700",
    alertIcon: "h-4 w-4 text-rose-500 shrink-0 mt-0.5",
    footerAudit: "mt-5 pt-3.5 border-t border-slate-100 flex items-center justify-center gap-1.5 text-[11px] text-slate-500",
    testCredentialsBox: "mt-4 max-w-md w-full bg-white border border-slate-200 rounded-xl p-3 text-[11px] text-slate-600 flex flex-col gap-1 shadow-xs",
    testCredentialsGrid: "grid grid-cols-3 gap-2 text-center pt-2 border-t border-slate-100",
    testCredentialItem: "bg-slate-50 border border-slate-200/80 p-2 rounded-lg",
  },
  dashboard: {
    metricsGrid: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3.5",
    metricCard: "bg-white border border-slate-200/90 rounded-lg p-4 shadow-2xs hover:shadow-xs transition-shadow flex flex-col justify-between",
    metricTop: "flex items-center justify-between",
    metricIconBox: "w-8 h-8 rounded-lg bg-blue-50 text-[#0066FF] flex items-center justify-center font-bold shadow-2xs",
    metricValue: "text-2xl font-bold text-slate-900 tracking-tight mt-2.5",
    metricLabel: "text-xs font-semibold text-slate-700 mt-0.5",
    metricSubtext: "text-[11px] text-slate-500 mt-1 flex items-center gap-1.5",
    grid: "grid grid-cols-1 lg:grid-cols-3 gap-3.5 mt-3.5",
    mainSection: "lg:col-span-2 space-y-3.5",
    sideSection: "space-y-3.5",
    panelCard: "bg-white border border-slate-200/90 rounded-lg p-4 shadow-2xs",
    panelHeader: "flex items-center justify-between border-b border-slate-100 pb-2.5 mb-3",
    panelTitle: "text-xs font-bold text-slate-900 tracking-tight flex items-center gap-2",
  },
  toast: {
    container: "fixed top-14 right-5 z-50 flex flex-col gap-2 max-w-sm w-full pointer-events-none",
    base: "pointer-events-auto flex items-start gap-3 p-3.5 rounded-lg bg-white border shadow-lg transition-all duration-300 transform translate-y-0",
    success: "border-emerald-200 text-slate-800 shadow-emerald-500/10",
    error: "border-rose-200 text-slate-800 shadow-rose-500/10",
    info: "border-blue-200 text-slate-800 shadow-blue-500/10",
    iconSuccess: "w-5 h-5 text-emerald-600 shrink-0 mt-0.5",
    iconError: "w-5 h-5 text-rose-600 shrink-0 mt-0.5",
    iconInfo: "w-5 h-5 text-blue-600 shrink-0 mt-0.5",
    content: "flex-1 min-w-0",
    title: "text-xs font-bold leading-none mb-1 text-slate-900",
    message: "text-xs text-slate-600 leading-relaxed",
    closeBtn: "shrink-0 p-1 text-slate-400 hover:text-slate-700 rounded hover:bg-slate-100 transition-colors cursor-pointer",
  },
  matrix: {
    bannerRoot: "p-3.5 bg-gradient-to-r from-purple-50 via-purple-50/50 to-white border border-purple-200/80 rounded-lg flex items-start gap-3 shadow-2xs",
    bannerGov: "p-3.5 bg-gradient-to-r from-[#EFF6FC] via-[#EFF6FC]/60 to-white border border-[#C7E0F4] rounded-lg flex flex-col md:flex-row items-start md:items-center justify-between gap-3 shadow-2xs",
    moduleCard: "bg-white border border-slate-200/90 rounded-lg shadow-2xs overflow-hidden transition-all",
    moduleHeader: "flex items-center justify-between px-4 py-3 bg-[#F8FAFC] border-b border-slate-200/80 select-none",
    moduleNumberPill: "w-5 h-5 rounded-md bg-[#0066FF] text-white flex items-center justify-center text-[10px] font-bold shadow-2xs",
    moduleSlugBadge: "text-[11px] font-mono text-slate-400 bg-white px-1.5 py-0.5 rounded border border-slate-200",
    submoduleCard: "space-y-3 bg-[#F8FAFC]/60 p-3.5 rounded-lg border border-slate-200/70",
    submoduleHeader: "flex items-center justify-between border-b border-slate-200/70 pb-2",
    submoduleNumberPill: "px-1.5 py-0.5 rounded bg-slate-200 text-slate-700 font-mono text-[10px] font-bold",
    submoduleSlugText: "text-[10px] font-mono text-slate-400",
    resourceCard: "bg-white p-3 rounded-lg border border-slate-200/90 shadow-2xs space-y-2.5 hover:border-blue-200 transition-colors",
    resourceHeader: "flex items-center justify-between border-b border-slate-100 pb-2",
    actionRow: "group/item flex items-start gap-2.5 p-2 rounded-md transition-all border",
    actionRowChecked: "bg-blue-50/40 border-blue-100",
    actionRowUnchecked: "bg-white border-transparent hover:bg-slate-50 hover:border-slate-200/80",
    filterTrigger: "inline-flex items-center gap-1.5 px-3 py-1.5 h-8 text-xs font-medium rounded-md border transition-all cursor-pointer shadow-2xs whitespace-nowrap",
    filterTriggerActive: "border-blue-300 text-[#0066FF] bg-[#EFF6FC] hover:bg-blue-100/70 font-semibold",
    filterTriggerInactive: "border-slate-200 text-slate-700 bg-white hover:bg-slate-50 hover:text-slate-900",
    filterPopover: "absolute left-0 mt-1.5 w-72 min-w-[280px] bg-white border border-slate-200 rounded-lg shadow-lg z-50 py-1.5 text-xs animate-in fade-in slide-in-from-top-1 duration-150",
    filterPopoverHeader: "flex items-center justify-between px-3 py-1.5 border-b border-slate-100 bg-slate-50/70 font-bold text-slate-700 text-[11px] uppercase tracking-wider",
    filterPopoverItem: "flex items-center gap-2.5 px-3 py-2 hover:bg-slate-50 cursor-pointer select-none transition-colors group",
  },
} as const;
