/**
 * TraceFlow RMG — Centralized Easy-Readable & Zero-Confusion Text Constants
 * Strictly follows docs/04_Frontend_Developer/SRS_Human_Readable_Zero_Confusion_Text.md
 * and AGENTS.md UI/UX Engineering Rules.
 * 
 * 100% English UI Labels. Zero ambiguity, no developer jargon, no confusing filler text.
 */

export const UI_TEXT = {
  // Common Global Actions
  ACTIONS: {
    SAVE: "Save Changes",
    SAVE_DRAFT: "Save as Draft",
    DISCARD: "Discard",
    CANCEL: "Cancel",
    SUBMIT: "Submit",
    CONFIRM: "Confirm",
    DELETE: "Delete",
    EDIT: "Edit",
    VIEW: "View Details",
    FILTER: "Filter",
    RESET: "Reset",
    SEARCH: "Search",
    EXPORT_EXCEL: "Export to Excel",
    EXPORT_CSV: "Export to CSV",
    PRINT_BARCODE: "Print QR Barcode",
    CLOSE: "Close",
    BACK: "Back",
    NEXT: "Next",
    PREVIOUS: "Previous",
  },

  // ShellBar & Navigation Microcopy
  SHELL: {
    APP_NAME: "TraceFlow RMG",
    APP_TAGLINE: "Garment Traceability & Manufacturing ERP",
    COMPANY_SWITCHER_LABEL: "Current Factory Unit",
    SEARCH_PLACEHOLDER: "Search barcode, roll, style, or order... (Ctrl+K)",
    ONLINE_STATUS: "System Connected",
    OFFLINE_STATUS: "Offline Mode (Local Storage Active)",
    NOTIFICATIONS: "System Notifications",
    USER_MENU: "User Profile",
    SIGN_OUT: "Sign Out",
  },

  // DataTable Standard Pagination & Sorting Microcopy
  TABLE: {
    PER_PAGE: "Show per page:",
    PAGE_INFO: (current: number, total: number) => `Page ${current} of ${total}`,
    RECORD_SUMMARY: (from: number, to: number, total: number) =>
      `Showing ${from} to ${to} of ${total} records`,
    NO_DATA: "No matching records found.",
    SORTED_BY: (field: string, dir: "asc" | "desc") =>
      `Sorted by: ${field} (${dir.toUpperCase()})`,
    ACTIONS_COLUMN: "Actions",
  },

  // Form Field Standards & Helpers
  FORM: {
    SYSTEM_AUTO_BADGE: "System Auto",
    SYSTEM_AUTO_HELPER: "Identifier is automatically generated by the system.",
    REQUIRED_INDICATOR: "*",
    SELECT_PLACEHOLDER: (entity: string) => `Select ${entity}...`,
    SEARCH_PLACEHOLDER: (entity: string) => `Search by ${entity} name or code...`,
  },

  // Universal Lifecycle Status Badges
  STATUS: {
    ACTIVE: "Active",
    INACTIVE: "Inactive",
    DRAFT: "Draft",
    CONFIRMED: "Confirmed",
    IN_PROGRESS: "In Progress",
    IN_INSPECTION: "In Inspection",
    COMPLETED: "Completed",
    ON_HOLD: "On Hold",
    CANCELLED: "Cancelled",
    PASS: "Pass / Accepted",
    ALTER: "Alter / Rework",
    REJECT: "Rejected / Defect",
  },

  // Destructive Action & Confirmation Microcopy
  CONFIRMATIONS: {
    DELETE_TITLE: "Confirm Deletion",
    DELETE_WARNING: (entityName: string) =>
      `Are you sure you want to delete '${entityName}'? This action cannot be undone.`,
    REJECT_ROLL_TITLE: "Confirm Roll Rejection",
    REJECT_ROLL_WARNING: (rollCode: string) =>
      `Are you sure you want to mark Fabric Roll '${rollCode}' as Defective? It will be blocked from spreading and cutting.`,
  },

  // Feedback Messages
  FEEDBACK: {
    SAVED_SUCCESS: "Changes saved successfully.",
    CREATED_SUCCESS: (entity: string) => `${entity} created successfully.`,
    DELETED_SUCCESS: (entity: string) => `${entity} deleted successfully.`,
    SERVER_VALIDATION_HEADER: "Please review and correct the errors below:",
    NETWORK_ERROR: "Unable to reach server. Please check your network connection.",
  },
} as const;
