<?php

namespace App\Domains\MasterData\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreBuyerRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Pure Server-Side Validation.
     * Code is strictly auto-generated by backend.
     */
    public function rules(): array
    {
        return [
            'company_id'      => ['required', 'integer', 'exists:companies,id'],
            'name'            => ['required', 'string', 'min:2', 'max:150'],
            'country'         => ['required', 'string', 'min:2', 'max:100'],
            'contact_person'  => ['nullable', 'string', 'max:100'],
            'email'           => ['nullable', 'email', 'max:100'],
            'phone'           => ['nullable', 'string', 'max:30'],
            'address'         => ['nullable', 'string', 'max:500'],
            'payment_terms'   => ['nullable', 'string', 'max:60'],
            'is_active'       => ['sometimes', 'boolean'],
            'brands'          => ['nullable', 'array'],
            'brands.*.name'   => ['required_with:brands', 'string', 'min:1', 'max:100'],
            'brands.*.code'   => ['nullable', 'string', 'max:30'],
        ];
    }

    public function messages(): array
    {
        return [
            'company_id.required'   => 'Company selection is required.',
            'company_id.exists'     => 'Selected company does not exist.',
            'name.required'         => 'Buyer name is required.',
            'country.required'      => 'Country is required.',
            'email.email'           => 'Please provide a valid email address.',
            'brands.*.name.required_with' => 'Each added brand must have a name.',
        ];
    }
}
